### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by hasindu2008** [BonsonW/slow5curl#4]
Google has sunset page.link short URL. So the following does not work.
https://github.com/BonsonW/slow5curl/blob/095341720b0b89098aae2937a1092235b3ab7102/src_tool/cmd.h#L73

I have got a domain to replace this page.link things. Can you please replace it with the following:
https://slow5.bioinf.science/slow5curl

**Comment by BonsonW** [comment]
fixed in dev
